<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <RestoreLockedMode Condition="'$(ContinuousIntegrationBuild)' == 'true'">true</RestoreLockedMode>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Configurations>Debug;Release;Debug UWP;Release UWP</Configurations>
    <TargetFramework>net472-windows</TargetFramework>
    <RootNamespace>WireSockUI.Tests</RootNamespace>
    <AssemblyName>WireSockUI.Tests</AssemblyName>
    <Platforms>AnyCPU;x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants Condition=" $(Configuration.Contains('UWP')) ">$(DefineConstants);WIRESOCKUI_ENABLE_UWP</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WireSockUI\WireSockUI.csproj"
                      AdditionalProperties="WireSockUIAllowManagedOnlyBuild=true" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
